version: '3'

services:
  app:
    build: .
    ports:
      - "443:443"
    depends_on:
      - db
    environment:
      - KEY_VAULT_URL=${KEY_VAULT_URL}
      # Environment variables as fallbacks if Key Vault is not accessible
      - DB-USER=demo_admin
      - DB-PASSWORD=AzureAzure123!
      - DB-HOST=ai-demos-pg.postgres.database.azure.com
      - DB-PORT=5432
      - DB-NAME=demoapp
      - ENTRA-CLIENT-ID=45b7c543-e98c-493c-b835-7f9566812b13
      - ENTRA-CLIENT-SECRET = 1js8Q~FGsH1hAL7VqEZtVSgpGo6XxhrwSnDLddlg
      - ENTRA-TENANT-ID = 4c585a33-3574-42d3-86a8-13d7b5c36f8e
      - COSMOS-ENDPOINT="https://aidemo-demoapp.documents.azure.com:443/"
      - COSMOS-KEY= "cIBoacwPNpMqxcmhTWj27hyw7Mobo2VkzLchhyirlk5anvr5Z1P6OFE8eHHuKQdubKSVBtwYEZFKACDbwIFVZw=="
      - COSMOS-DATABASE=chatapp
      - COSMOS-CONTAINER=messages
      - AZURE_OPENAI_ENDPOINT="https://ai-demos-aoai-kedamm.openai.azure.com/"
      - AZURE_OPENAI_KEY="a222855ee35c499082c7c003a8cfb4d8"
      - AZURE_OPENAI_DEPLOYMENT="gpt-4o"
      - AZURE_OPENAI_API_VERSION="2024-10-01-preview"
      - KEY_VAULT_URL="https://aieu2project4459441412.vault.azure.net/"
      - DATABASE_URL="ai-demos-pg.postgres.database.azure.com"
      - AZURE_CONTAINER_URL="https://aiblobeu2.blob.core.windows.net/"
      - AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=aiblobeu2;AccountKey=5c+MCepmLcS0hyax+lyXWhTtR7CCfR0y795lgCWuwGUIPRjBRIqM2iBwjcGmuW8Q0LzEnZZy+1jA+AStF1lMag==;EndpointSuffix=core.windows.net"
      - AZURE_STORAGE_CONTAINER_NAME="userfiles"


    volumes:
      - app-data:/data
    # For local development, use Azure CLI credentials
    # Comment this out if using managed identity in production
    env_file:
      - .env.local

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=demo_admin
      - POSTGRES_PASSWORD=AzureAzure123!
      - POSTGRES_DB=demoapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  app-data: